### ISSUE TITLE
Shiny app project contents - .git or not?

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#11]
Book: ![image](https://github.com/mjfrigaard/shinyap/assets/85294667/740e27c5-44ab-4606-a269-883a60f1b70d)

My session: 
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/9af0a107-afd9-43ac-882a-a6d69c26ae19)

**Comment by mjfrigaard** [comment]
The `.gitignore` is an indication Git was selected in the new project wizard. The picture indicates I selected a Git repo and opted to not include `renv` (as does the folder tree).
