### ISSUE TITLE
Cannot run app: Introduction - Shiny apps - Updated movies app project contents

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#12]
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/e2fffb35-a4e7-46a8-bf4e-9fb18287001b)

**Comment by esimms999-gsk** [comment]
Are you running lines 3 and 4, above, before running the app? And then commenting them out?

**Comment by mjfrigaard** [comment]
Yes--run lines [3](https://github.com/mjfrigaard/shinyap/blob/f114dc300537b65777219baac58039d9120d1553/shiny.qmd#L347) and [4](https://github.com/mjfrigaard/shinyap/blob/f114dc300537b65777219baac58039d9120d1553/shiny.qmd#L348) (if these packages are not already installed), then comment out
