### ISSUE TITLE
DESCRIPTION has invalid line

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#13]
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/cee955df-a112-4e9c-89de-90c4b36ae5fb)

![image](https://github.com/mjfrigaard/shinyap/assets/85294667/86c7a211-7dfa-475a-8218-8049218fe83f)

**Comment by esimms999-gsk** [comment]
When I remove this line, the error goes away.

**Comment by mjfrigaard** [comment]
Yes--the note in the margin mentions leaving an `<empty final line>` in the `DESCRIPTION` file, but I'll add a sentence that you should be deleting _actual_ `<empty final line>`

**Comment by mjfrigaard** [comment]
[New 'delete me' comment](https://github.com/mjfrigaard/shinyap/blob/bc10b370347d83dfeb18aded4a82f7fd66e4a296/shiny.qmd#L436)
