### ISSUE TITLE
utils.R has been moved to R/ and cannot be found

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#14]
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/eaecfc1d-92b3-44e5-ba32-e5d04e907595)

I needed to change this to R/utils.R

In the book, you removed the source and load at some point:

![image](https://github.com/mjfrigaard/shinyap/assets/85294667/518afbad-a84c-4fe2-8668-34ff2aa5598c)

**Comment by mjfrigaard** [comment]
The source() and load() aren't needed in that version. The standalone app function is added to the [projApp branch](https://github.com/mjfrigaard/projApp/tree/03_projApp), which has an R folder (so need to call `source()`) and the data is [loaded in the module.](https://github.com/mjfrigaard/projApp/blob/22209d695f72cc10c887a071c0832ea5981f2707/R/mod_scatter_display.R#L20)

**Comment by mjfrigaard** [comment]
Addressed in new updates.
