### ISSUE TITLE
Introduction - Shiny apps - Updated movies app project contents: Confusion with comments and first showcase results

### ISSUE THREAD

**Issue by esimms999** [mjfrigaard/shinyap#3]
What needs to be commented out in the app.R header after installing? The pkgs and install.packages lines? What about the library statements? Commenting the load("movies.RData") line makes the app crash. **Not** commentiing the source("utils.R") makes it crash.

![image](https://github.com/mjfrigaard/shinyap/assets/10915780/ec08341b-7c5e-4e5a-9323-ff4c8d6f5060)

With Showcase, you display this:

![image](https://github.com/mjfrigaard/shinyap/assets/10915780/2ccffd31-9322-4381-832e-b00d730d59d2)

But what I am seeing with my best guess commenting is this:

![image](https://github.com/mjfrigaard/shinyap/assets/10915780/ca3957e1-1338-42ab-9a0b-36642f271a7d)

You have movies_app <- function .... I don't have that. You don't have anything of the load("movies.RData") and source("utils.R") ... looks like those lines were removed at some point. I think you are showing code a couple of steps ahead of where it is when I am following your guide.

**Comment by mjfrigaard** [comment]
The section referring to the [code header](https://mjfrigaard.github.io/shinyap/shiny.html#updated-movies-app-project-contents) in `app.R` requires the header (hence the specific callout box). 

The image of showcase mode is misleading (it's meant to only demonstrate the showcase feature), so it's been removed. But you don't need the call to `source()` if you've followed along and converted the application into modules and placed all the `.R` files in the `R/` folder. The final [`app.R` file](https://mjfrigaard.shinyapps.io/projApp/) in this chapter doesn't need to `source()` any files or load the data (this is handled in the module). 

After installing the packages in `app.R` to your machine, comment this line out (like the one in the [deployed application](https://mjfrigaard.shinyapps.io/projApp/)).

**Comment by mjfrigaard** [comment]
Addressed in [commit](https://github.com/mjfrigaard/shinyap/commit/b3a00baeebd119e41d594e49e3b003905bd51afd)
