### ISSUE TITLE
Introduction - Shiny apps - Standalone app function: rsconnect directory

### ISSUE THREAD

**Issue by esimms999** [mjfrigaard/shinyap#5]
03_projApp and my own workspace do not have an rsconnect directory:

![image](https://github.com/mjfrigaard/shinyap/assets/10915780/fe6f95d3-d63a-43c4-85c4-56eafb54949c)

**Comment by mjfrigaard** [comment]
The current sentence reads, "*The deployed files of `projApp` are below:*"

But I will add a margin comment about the removal of `rsconnect/` folder.
