### ISSUE TITLE
Introduction -> Shiny apps section: all figures have two captions

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#5]
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/34bb81ef-e328-48eb-bccf-83dcc5f764b9)

**Comment by mjfrigaard** [comment]
One is a figure div, the other is a figure caption. This is so they can be referenced as figure 1.a figure 1.b, figure 2.a, figure 2.b, etc.

**Comment by mjfrigaard** [comment]
See [figures section of quarto documentation.](https://quarto.org/docs/authoring/figures.html#subfigures)
