### ISSUE TITLE
Quotes - where from?

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#6]
![image](https://github.com/mjfrigaard/shinyap/assets/85294667/2643793f-07b9-406c-8a5f-04157e35a560)

![image](https://github.com/mjfrigaard/shinyap/assets/85294667/796f5558-a3be-4290-b199-3d1e451694b1)

**Comment by mjfrigaard** [comment]
The first is from the book author (i.e., guiding principle), but the second is from the help files for shiny::NS() (which needs to be hyperlinked).

**Comment by mjfrigaard** [comment]
Fixed in latest release.

**Comment by mjfrigaard** [comment]
See [here](https://github.com/mjfrigaard/shinyap/blob/bc10b370347d83dfeb18aded4a82f7fd66e4a296/intro.qmd#L25) and [here](https://github.com/mjfrigaard/shinyap/blob/f114dc300537b65777219baac58039d9120d1553/shiny.qmd#L551)
