### ISSUE TITLE
"end zzz.qmd" at end of some chapters, e.g. Introduction -> Shiny apps

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#7]
"end shiny.qmd" - should this be here?

![image](https://github.com/mjfrigaard/shinyap/assets/85294667/dc73d9ec-ab57-4d63-ad22-369e4e8d29ac)

**Comment by mjfrigaard** [comment]
This was some manual debugging with quarto to try and figure out the following:

```
Warning message:
In readLines(input) : incomplete final line found on 'intro.qmd'
```

Will be removed in future versions.

**Comment by mjfrigaard** [comment]
Warning message to be addressed in future release of quarto.
