### ISSUE TITLE
Introduction -> Shiny apps: showcase mode

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#8]
An example of showcase mode is shown further down, but it should have some quick explanation when it is first mentioned (or mention that it will be explained soon).

![image](https://github.com/mjfrigaard/shinyap/assets/85294667/53b70dee-7fc3-45e2-95bc-44d942cdd8b0)

**Comment by mjfrigaard** [comment]
I will link to the shiny article explaining [ShowcaseMode/DESCRIPTION](https://shiny.posit.co/r/articles/build/display-modes/).
